version: '2'
services:
    chipmunk:
        build:
            context: ./var/docker/db
            args:
                HOST_UID: ${HOST_UID}
        volumes:
            - ./var/db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: docker
            MYSQL_DATABASE: mttblog
            MYSQL_USER: mttblog
            MYSQL_PASSWORD: docker

    lizard:
        build:
            context: ./var/docker/web
            # dockerfile: prod/Dockerfile
            args:
                HOST_UID: ${HOST_UID}
        volumes:
            - .:/var/www/html
        ports:
            - "80:80"
        links:
            - chipmunk
            - mailcatcher
        depends_on:
            - chipmunk
            - mailcatcher
        environment:
            APPLICATION_ENV: development

    aardvark:
        build: ./var/docker/dbadmin
        ports:
            - "8088:80"
        links:
            - chipmunk
        depends_on:
            - chipmunk
        environment:
            PMA_HOST: chipmunk
            PMA_USER: root
            PMA_PASSWORD: docker

    mailcatcher:
        image: xelbot/mailcatcher
        ports:
            - "1080:1080"
