<?php
    $this->headScript()->appendFile('/js/topic_script_20130319.min.js', 'text/javascript', array());
    $options = Zend_Registry::get('options');
?>
<article>
    <time datetime="<?php echo $this->viewDateTime($this->post->time_created, DateTime::W3C); ?>">
        <?php echo $this->viewDateTime($this->post->time_created); ?>
    </time>
    <h1><a href="<?php echo $this->url(array('url' => $this->post->cat_url), 'category-page', true); ?>"><?php
            echo $this->post->cat_name; ?></a> &rarr; <?php echo $this->post->title; ?></h1>
    <div class="text-post">
        <?php echo $this->post->text_post; ?>
    </div>
    <a href="<?php echo $options['social_link']['googleplus']; ?>?rel=author" class="author-link">
        <img alt="g-plus-icon" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAB1klEQVQoU2O4621JEmK442Vxw9P8Jm501skQiM45GQLVAFUy3PKwu1M/6ePxk9/e/f0PBx+uvKr0vuZuBkSnHQyAwmccDYHsq25mDK8uvfm+qeSGh8nlwMCnex4B5X4dar7uZnIZhk466AMFTznqA0UuuZow/P9//qGf0SUXo4tA5BH77iVQ9vPrEssT9npwBBSCs4EaDtx2NTjnBEW3lt0HSn9dFHnK0xLIwARADU8eJeidttc7ZQdC51p2gayYGXzEWhuOgCIwtg7D/7//v63POmGjcwyMLsy48P/XpbvBUC5Q5JCVFlADkASyj9poM3z9BuR+eruo6Gyw69nKCZ/e3HtWbXvQShOO9llqAFXstdA4YKkJRAwnguNuzlvyYtfez++A4t9f1NvtNVPfg4R2mapBEESQ4bC5+g4T1R0mwU/e/P/3/8OjAhMwFydiOGCiutVQeYuh7tmNL/7//P//x90HpU5gEeyI4Xzb1Ef7DzzbuOzBmmWPTz74BwrI9y+7QrfoK25ERRvAXIave3sOuamv05VfD0Jah7q3fv8F0nM3WQcsgkAQNQwnTORXacsio82Fa38AA25xOJo4hMuwT1durbbMGhQU+fDr/zddjqiCUDUAmzuTnmNga6gAAAAASUVORK5CYII="/>
    </a>
    <?php
        $cacheOutput = Zend_Registry::get('cacheOutput');
        $key         = 'tag_post_' . $this->post->id;
        if (!($cacheOutput->start($key))) {
            $tags = $this->post->findManyToManyRowset('Application_Model_Tags', 'Application_Model_PostsTags');
            if (count($tags)) {
                ?><div class="tags">Теги: <?php echo $this->viewTags($tags); ?></div><?php
            }
            $cacheOutput->end();
        }
    ?>
</article>
<?php if (!$this->post->hide && getenv('APPLICATION_ENV') != 'testing') {
/*
<section id="social">
    <div id="fb-root"></div>
        <script type="text/javascript">
            (function (d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s);
                js.id = id;
                js.src = "//connect.facebook.net/ru_RU/all.js#xfbml=1";
                fjs.parentNode.insertBefore(js, fjs);
            } (document, 'script', 'facebook-jssdk'));
        </script>
    <div class="facebook">
        <div class="fb-like" data-send="true" data-layout="button_count" data-width="220" data-show-faces="false"></div>
    </div>
    <div class="googleplus">
        <div class="g-plusone" data-size="medium"></div>
        <script type="text/javascript">
            window.___gcfg = { lang: 'ru' };
            (function () {
                var po = document.createElement('script');
                po.type = 'text/javascript';
                po.async = true;
                po.src = 'https://apis.google.com/js/plusone.js';
                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(po, s);
            })();
        </script>
    </div>
    <div class="twitter">
        <a href="https://twitter.com/share" class="twitter-share-button" data-lang="ru">Твиттер</a>
        <script>
            !function (d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (!d.getElementById(id)) {
                    js = d.createElement(s);
                    js.id = id;
                    js.src = "//platform.twitter.com/widgets.js";
                    fjs.parentNode.insertBefore(js, fjs);
                }
            } (document, "script", "twitter-wjs");
        </script>
    </div>
    <div class="clear-left"></div>
</section>
 */ ?>
<section id="dis_comm">
    <div id="disqus_thread"></div>
    <?php
        $topicUrl = $this->url(array('url' => $this->post->url), 'topic_url', true);
    ?>
    <script type="text/javascript">
        var disqus_shortname = '<?php echo $options['disqus']['shortname']; ?>';
        var disqus_identifier = '<?php echo $topicUrl; ?>';
        var disqus_url = '<?php echo BASE_URL . $topicUrl; ?>';
        var disqus_title = <?php echo json_encode($this->post->title); ?>;
        var disqus_config = function () {
            this.language = 'ru';
        };

        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</section>
<?php } ?>
<section id="comments">
    <div id="noscript">
        Учтите, что комментарии добавляются только при включённом JavaScript в браузере.
        В ином случае информация хоть и не пропадёт бесследно, но будет отправлена в спам и вряд ли хоть кто-нибудь её увидит.
    </div>
    <div id="all-comments">
    <?php
        if (Zend_Auth::getInstance()->hasIdentity()) {
            $keyComments = 'comments_post_auth_' . $this->post->id;
        } else {
            $keyComments = 'comments_post_' . $this->post->id;
        }
        if (!($cacheOutput->start($keyComments))) {
            $comments = $this->post->getComments();
            echo $this->partialLoop('index/comments.phtml', $comments);
            $cacheOutput->end();
        }
    ?>
    <?php
        $countComments = (int) $this->post->comments_count;
        if ($countComments) {
    ?>
        <div id="topic-reply">
            <?php echo $this->commentsCountString($countComments); ?> <span>Написать что-нибудь</span>
        </div>
        <div id="comment-form-wrapper"></div>
    <?php } ?>
    </div>
    <div id="comment_add">
        <?php echo $this->partial('index/formcomment.phtml', array(
            'form' => $this->form,
        )); ?>
    </div>
</section>
<script type="text/javascript">
    var auth_comment = <?php echo (Zend_Auth::getInstance()->hasIdentity()) ? 'true' : 'false'; ?>;
    var addCommentLink = '<?php echo $this->url(array(), 'add_ajax_comment'); ?>';
</script>
