<?php
    $styleString = <<<STYLE
.dhx_chart { font-family: "Consolas","Lucida Console",monospace; font-size: 10.5pt; }
.dhx_canvas_text { overflow: visible; }
.dhx_tooltip { font-family:"Consolas","Lucida Console",monospace; font-size:10.5pt; background-color: #FFF; background-color: rgba(255,255,255,0.75); padding:2px 4px; border:1px solid #DCE7B4; }
#chart_container { width:100%; height:320px; }
STYLE;

    $this->headScript()
        ->appendFile('/js/dhtmlx/chart/dhtmlxchart.js', 'text/javascript', array())
        ->appendFile('/js/statistic.js', 'text/javascript', array());
    $this->headLink()->appendStylesheet('/js/dhtmlx/chart/dhtmlxchart.css');
    $this->headStyle()->appendStyle($styleString);
?>
<article>
    <h2>Статистика</h2>
    <div class="text-post">
        <div class="quote-div">&ldquo;Существуют три вида лжи: ложь,<br/>наглая ложь и статистика.&rdquo;<br/>Марк Твен</div>
        <div id="chart_container"></div>
        <p>На этом графике отображены просмотры статей за последние две недели.
            Поисковые машины и прочие роботы не учитываются.
            Однако мой метод выявления ботов далеко не совершенен, некоторые роботы притворяются людьми, а некоторые люди ведут себя
            хуже роботов, т.е. данные не совсем достоверные.</p>
    </div>
<?php
    $cacheOutput = Zend_Registry::get('cacheOutput');
    if (!($cacheOutput->start('commentators_stats'))) {

        $comentatorsTable = new Application_Model_Commentators();
        $comentators = $comentatorsTable->getCommentatorsForStatistic(8);

        if (count($comentators)) { ?>
    <h2>Комментаторы</h2>
    <div class="text-post article-stats">
        <p>Ниже представлены самые активные комментаторы за всё время существования блога.</p>
        <div id="comentators">
            <?php foreach ($comentators as $item) { ?>
            <div class="comentators-item-wrap">
                <div class="comentators-item">
                    <img src="<?php echo $this->getAvatar($item); ?>" width="80" height="80" alt="avatar"/>
                    <div class="comentators-info">
                        <?php if ($item['website']) { ?>
                            <a href="<?php echo $item['website']; ?>" class="ext"><?php echo $item['name']; ?></a>
                        <?php } else { ?>
                            <span><?php echo $item['name']; ?></span>
                        <?php } ?>
                        <br/><?php echo $this->commentsCountString($item['count']); ?>
                    </div>
                    <div class="clear-left"></div>
                </div>
            </div>
            <?php } ?>
            <div class="clear-left"></div>
        </div>
    </div>
    <?php
        }
        $cacheOutput->end();
    }
?>
    <h2>Записи</h2>
    <div class="text-post article-stats">
        <?php if (count($this->weekArticle)) { ?>
        <p>Самые посещаемые статьи за последние две недели.</p>
        <ul>
            <?php foreach ($this->weekArticle as $item) { ?>
            <li>
                <a href="<?php echo $this->url(array('url' => $item['url']), 'topic_url'); ?>"><?php echo $this->cutSubString($item['title'], 60); ?></a>
                [<?php echo $this->razCountString($item['count']); ?>]
            </li>
            <?php } ?>
        </ul>
        <?php } ?>
        <p>Самые посещаемые статьи за всё время.</p>
        <ul>
            <?php foreach ($this->allArticle as $item) { ?>
            <li>
                <a href="<?php echo $this->url(array('url' => $item['url']), 'topic_url'); ?>"><?php echo $this->cutSubString($item['title'], 60); ?></a>
                [<?php echo $this->razCountString($item['views']); ?>]
            </li>
            <?php } ?>
        </ul>
    </div>
</article>
<script type="text/javascript">
    var cartData = <?php echo json_encode($this->trackingData); ?>;
</script>
