<nav class="ym-vlist">
    <h6 class="ym-vtitle">Управление</h6>
    <ul>
        <li><a href="<?php echo $this->url(array(), 'admin_topic', true); ?>">Записи</a></li>
        <li><a href="<?php echo $this->url(array(), 'admin_category', true); ?>">Категории</a></li>
        <li><a href="/admin/twitter">Twitter</a></li>
        <!--
        <li><span>Link 3</span>
            <ul>
                <li><a href="#">Link 3.1</a></li>
                <li class="active"><strong>Link 3.2</strong></li>
                <li><a href="#">Link 3.3</a></li>
            </ul>
        </li>
        <li><a href="#">Link 4</a></li>
        <li><a href="#">Link 5</a></li>
        -->
    </ul>
</nav>