<?php
    $urlString = $this->url(array('url' => 'd73bvckd6dhj'), 'category-page', true);

    function renderChild($id, $arrayValue, $url)
    {
        $tempArray = array();
        foreach ($arrayValue as $item) {
            if ($item['parent_id'] == $id) {
                $tempArray[] = $item;
            }
        }

        if (count($tempArray)) {
            echo '<ul>';
            foreach ($tempArray as $item) {
                echo '<li><a href="' . str_replace('d73bvckd6dhj', $item['url'], $url) . '">' . $item['name'] . '</a>';
                renderChild($item['id'], $arrayValue, $url);
                echo '</li>';
            }
            echo '</ul>';
        }
    }

    $options = Zend_Registry::get('options');
?>
<div class="category-list-header">
    Категории:
</div>
<div class="category-list">
    <?php renderChild(0, $this->category, $urlString); ?>
</div>
<?php
    $tagsObject = new Application_Model_Tags();
    $tags = $tagsObject->getTagCloudData();

    $tagsArray = array();
    foreach ($tags as $item) {
        $tagsArray[] = array(
            'title'  => $item['name'],
            'weight' => $item['count'],
            'params' => array(
                'url' => $this->url(array(
                    'url' => $item['url'],
                ), 'tag-page', true)
            )
        );
    }

    $cloud = new Zend_Tag_Cloud(array(
        'tags' => $tagsArray,
        'TagDecorator' => array(
            'decorator' => 'HtmlTag',
            'options' => array(
                'fontSizeUnit' => 'px',
                'minFontSize' => 12,
                'maxFontSize' => 24,
            ),
        ),
    ));
?>
<div class="category-list-header">
    Теги:
</div>
<div class="tag-list">
    <?php echo $cloud; ?>
</div>

<div class="category-list-header">
    Статистика:
</div>
<div class="tag-list">
    <?php
        if (!in_array(getenv('APPLICATION_ENV'), array('development', 'testing'))) {
            $flagcounterCode = $options['sys_parameters']['flagcounter'];
            $yandexMetrika = $options['sys_parameters']['yandex_metrika'];
    ?>
        <a href="http://s09.flagcounter.com/more/<?php echo $flagcounterCode; ?>">
            <img src="https://s09.flagcounter.com/count/<?php echo $flagcounterCode; ?>/bg_000000/txt_FFFFFF/border_FFFFFF/columns_2/maxflags_8/viewers_3/labels_1/pageviews_1/"
            alt="free counters" class="no-style"/>
        </a>
        <?php /*
        <script>
            (function (d, w, c) {
                (w[c] = w[c] || []).push(function() {
                    try {
                        w.yaCounter<?php echo $yandexMetrika; ?> = new Ya.Metrika({
                            id: <?php echo $yandexMetrika; ?>,
                            trackLinks: true,
                            accurateTrackBounce: true});
                    } catch(e) { }
                });

                var n = d.getElementsByTagName("script")[0],
                    s = d.createElement("script"),
                    f = function () { n.parentNode.insertBefore(s, n); };
                s.type = "text/javascript";
                s.async = true;
                s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

                if (w.opera == "[object Opera]") {
                    d.addEventListener("DOMContentLoaded", f, false);
                } else { f(); }
            })(document, window, "yandex_metrika_callbacks");
        </script>
        <noscript>
            <div>
                <img src="//mc.yandex.ru/watch/<?php echo $yandexMetrika; ?>"
                     style="position:absolute; left:-9999px;" alt="" />
            </div>
        </noscript> */ ?>
    <?php } else { ?>
        <img src="/img/dev_flagcounter.png" alt="free counters" class="no-style"/>
    <?php } ?>
</div>
