<?php if ($this->twitterBlock) { ?>
    <div id="twitter-header">
        <img src="<?php echo $this->profileImage; ?>" alt="" width="32" height="32" />
        <div class="desc">
            <a href="https://twitter.com/intent/user?screen_name=<?php echo $this->screenName; ?>">@<?php echo $this->screenName; ?></a><br/>
            <?php echo $this->location; ?>
        </div>
        <div class="clear-left"></div>
    </div>
    <div id="twitter-status-list">
        <?php
            $twittCount = 0;
            foreach ($this->twitterStatus->toValue() as $status) {
                $dateTime = date_create_from_format('D M d H:i:s O Y', $status->created_at);
                if ($twittCount == 5) {
                    break;
                }
                $twittCount++;
        ?>
        <div class="twitter-status">
            <?php echo $this->twitterText($status->text); ?>
            <a class="twitter_time" href="https://twitter.com/<?php
                echo $this->screenName;
            ?>/status/<?php echo $status->id; ?>"><?php echo date_format($dateTime, 'd.m.Y'); ?></a>
        </div>
        <?php } ?>
    </div>
    <div id="twitter-footer">
        <a href="https://twitter.com"><img src="<?php echo IMG_DOMAIN; ?>/twitter_bird.png" alt=""/></a>
        <span><a href="https://twitter.com/<?php echo $this->screenName; ?>">Присоединяйтесь</a></span>
    </div>
<?php } ?>