<?php if ($this->pageCount > 1) { ?>
<div class="paginator">

<?php if (isset($this->previous)) { ?>
  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">&larr;</a>
<?php } ?>

<?php foreach ($this->pagesInRange as $page) { ?>
  <?php if ($page != $this->current) { ?>
    <a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
  <?php } else { ?>
    <span><?php echo $page; ?></span>
  <?php } ?>
<?php } ?>
 
<?php if (isset($this->next)) { ?>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>">&rarr;</a>
<?php } ?>

</div>
<?php } ?>