<?php echo $this->doctype() . PHP_EOL; ?>
<html lang="ru">
<head>
<?php
    $this->headMeta()
        ->setCharset('utf-8')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        //->appendName('viewport', 'width=device-width, initial-scale=1')
        ->appendName('author', 'morontt');
    if (isset($this->metaDescription) && $this->metaDescription) {
        $this->headMeta()->appendName('description', $this->metaDescription);
    }
    echo $this->headMeta() . PHP_EOL;
    $this->headTitle($this->browsertitle);
    $this->headTitle($this->layout()->title);
    $this->headTitle()->setSeparator(' » ');
    echo $this->headTitle() . PHP_EOL; ?>
<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#859c40">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#859c40">
<?php
    $this->headLink(array(
        'rel'   => 'alternate',
        'title' => 'RSS',
        'href'  => BASE_URL . '/feed/rss',
        'type'  => 'application/rss+xml',
    ));
    $this->headLink(array(
        'rel'   => 'alternate',
        'title' => 'Atom',
        'href'  => BASE_URL . '/feed/atom',
        'type'  => 'application/atom+xml',
    ));
    $this->headLink(array(
        'rel'   => 'dns-prefetch',
        'href'  => '//www.google-analytics.com',
    ));
//    $this->headLink(array(
//        'rel'   => 'dns-prefetch',
//        'href'  => '//mc.yandex.ru',
//    ));
    $this->headLink(array(
        'rel'   => 'dns-prefetch',
        'href'  => '//s09.flagcounter.com',
    ));
    $this->headLink(array(
        'rel'   => 'author',
        'href'  => '/humans.txt',
        'type'  => 'text/plain',
    ));
    $this->headLink()
        ->prependStylesheet('/css/yaml/core/iehacks.min.css', 'screen', 'lte IE 7')
        //->prependStylesheet('/css/main.css')
        //->prependStylesheet('/css/all.css')
        ->prependStylesheet('/css/main_20150713.min.css')
    ;
    echo $this->headLink() . PHP_EOL; ?>
<!--[if lt IE 9]><script type="text/javascript" src="//cdn.jsdelivr.net/html5shiv/3.7.2/html5shiv.min.js"></script><![endif]-->
<!--[if gte IE 7]>
<style type="text/css">
    #main .ym-wrapper { background: #DCE7B4; }
</style>
<![endif]-->
<!--[if IE 9]>
<style type="text/css">
    #main .ym-wrapper { background: url('/img/background/bg-main-ym-wrapper.svg'); }
</style>
<![endif]-->
<?php
    echo $this->headStyle() . PHP_EOL;

    if (!in_array(getenv('APPLICATION_ENV'), array('development', 'testing')) && !Zend_Auth::getInstance()->hasIdentity()) {
        $options = Zend_Registry::get('options');
        $googleAnalyticsCode = $options['sys_parameters']['googleanalytic'];
?>
<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', '<?php echo $googleAnalyticsCode; ?>']);
    _gaq.push(['_trackPageview']);
    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
</script>
<?php } ?>
</head>
<body>
    <header>
        <div class="ym-wrapper">
            <div class="ym-wbox">
                <span><?php echo $this->layout()->title; ?></span>
            </div>
        </div>
    </header>
    <nav id="navigation">
        <div class="ym-wrapper">
            <div class="ym-hlist">
                <?php
                    $cacheOutput = Zend_Registry::get('cacheOutput');
                    if (Zend_Auth::getInstance()->hasIdentity()) {
                        $menuKey = 'navigation_menu_auth_' . md5(serialize(Zend_Registry::get('requestParams')));
                        $sidebarKey = 'sidebar_auth';
                    } else {
                        $menuKey = 'navigation_menu_' . md5(serialize(Zend_Registry::get('requestParams')));
                        $sidebarKey = 'sidebar';
                    }
                    if (!($cacheOutput->start($menuKey))) {
                        echo $this->action('menu', 'navigation', null, array()) . PHP_EOL;
                        $cacheOutput->end();
                    }

                    $options = Zend_Registry::get('options');
                ?>
                <div id="social-links">
                    <a class="s-rss" href="<?php echo BASE_URL; ?>/feed/rss" title="RSS">rss</a>
                    <a class="s-fcb" href="<?php echo $options['social_link']['facebook']; ?>" title="facebook">facebook</a>
                    <a class="s-twt" href="<?php echo $options['social_link']['twitter']; ?>" title="twitter">twitter</a>
                    <a class="s-ins" href="<?php echo $options['social_link']['instagram']; ?>" title="instagram">instagram</a>
                    <a class="s-lj" href="<?php echo $options['social_link']['livejournal']; ?>" title="livejournal">livejournal</a>
                    <a class="s-git" href="<?php echo $options['social_link']['github']; ?>" title="github">github</a>
                    <a class="s-gp" href="<?php echo $options['social_link']['googleplus']; ?>" title="google+">googleplus</a>
                </div>
            </div>
        </div>
    </nav>
    <div id="main">
        <div class="ym-wrapper">
            <div class="ym-wbox">
                <div class="ym-column">
                    <section class="ym-col1">
                        <div class="ym-cbox">
                            <?php echo $this->layout()->content . PHP_EOL; ?>
                        </div>
                    </section>
                    <aside class="ym-col3">
                        <div class="ym-cbox">
                            <?php
                                if (!($cacheOutput->start($sidebarKey))) {
                                    echo $this->action('index', 'navigation', null, array()) . PHP_EOL;
                                    $cacheOutput->end();
                                }
                            ?>
                        </div>
                    </aside>
                </div>
            </div>
        </div>
    </div>
    <footer>
        <div class="ym-wrapper">
            <div class="ym-wbox">
                <div class="ym-grid">
                    <div class="ym-g33 ym-gl">
                        <div class="ym-gbox">
                            Layout based on <a href="http://www.yaml.de" class="ext">YAML</a>
                        </div>
                    </div>
                    <div class="ym-g33 ym-gl">
                        <div class="ym-gbox">
                            <a href="http://validator.w3.org/check?uri=<?php
                                $checkUrl = sprintf('https://%s%s', $_SERVER['HTTP_HOST'], $_SERVER['REQUEST_URI']);
                                echo urlencode($checkUrl); ?>"
                               title="Клацни здесь для проверки страницы"
                               class="ext">Valid HTML</a>
                        </div>
                    </div>
                    <div class="ym-g33 ym-gr">
                        <div class="ym-gbox">
                        <?php if (Zend_Auth::getInstance()->hasIdentity()) { ?>
                            <a href="<?php echo $this->url(array(), 'admin', true); ?>">Админка</a><br/>
                            <a href="<?php echo $this->url(array(), 'logout'); ?>">Выход</a>
                        <?php } else { ?>
                            <a href="<?php echo $this->url(array(), 'login'); ?>">Вход</a>
                        <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
<?php
    $this->headScript()
        ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js', 'text/javascript', array())
        ->prependFile('/js/syntaxhighlighter/shMain_20130218.js', 'text/javascript', array());

    echo $this->headScript() . PHP_EOL; ?>
    <script type="text/javascript">
        SyntaxHighlighter.all();

        $(function () {
            if (document.head) {
                var href_cache = {};

                $('a.reactive').hover(function () {
                    var keys = $(this).attr('href').match(/^[^#]+/);
                    var url = keys[0];

                    if (href_cache[url] === undefined) {
                        href_cache[url] = true;

                        var link = document.createElement('link');
                        link.rel = 'prefetch';
                        link.href = url;
                        document.head.appendChild(link);
                    }
                });
            }
        });
    </script>
</body>
</html>
