<?php
    $this->headTitle('Редактирование записи');

    $this->headScript()
        ->appendFile('/js/jquery-ui/jquery-ui.min.js', 'text/javascript', array())
        ->appendFile('/js/tags_autocomlete.js', 'text/javascript', array());
    $this->headLink()->appendStylesheet('/js/jquery-ui/themes/base/jquery.ui.all.css');
?>

<div id="view-content">
    <div style="text-align: right;">
        <a href="<?php echo $this->url(array('id' => $this->topicId), 'retwit'); ?>">Твитнуть</a>
    </div>
    <div class="theme">Редактирование записи</div>
    <div class="strsigninform">
        <?php echo $this->form; ?>
        <p>Используйте тег &lt;!-- cut --&gt;, если необходимо отделить краткое описание записи, остальное уйдёт под кат.</p>
    </div>
</div>
<script>
    var availableTags = <?php echo json_encode($this->availableTags); ?>;
</script>