<table width="100%" cellspacing="0" style="background-color: #859C40; color: #FFF; font-family: 'Consolas','Lucida Console',monospace; font-size: 12pt;">
    <tr height="56">
        <td style="padding: 0 35px;">
            <a style="color: #FFF200; text-decoration: none; font-family:'Consolas','Lucida Console',monospace;font-size:14pt;" href="<?php echo BASE_URL; ?>"><?php
                echo $this->headerTitle; ?></a>
        </td>
        <td align="right">
            <img src="<?php echo BASE_URL; ?>/img/logo_mail.png"/>
        </td>
    </tr>
</table>